praca/filmy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('filmy/', include('filmyweb.urls')),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

praca/filmyweb/urls.py
from django.urls import path
from filmyweb.views import wszystkie_filmy, nowy_film, edytuj_film, usun_film

urlpatterns = [
    path('wszystkie/', wszystkie_filmy, name="wszystkie_filmy"),
    path('nowy/', nowy_film, name="nowy_film"),
    path('edytuj/<int:id>/', edytuj_film, name="edytuj_film"),
    path('usun/<int:id>/', usun_film, name="usun_film"),
]

praca/filmyweb/models.py
from django.db import models

class Film(models.Model):
    tytul = models.CharField(max_length=64, blank=False, unique=True)
    rok = models.PositiveSmallIntegerField(default=2000)
    opis = models.TextField()
    premiera = models.DateField(null=True, blank=True)
    imdb_rating = models.DecimalField(max_digits=4, decimal_places=2)
    plakat = models.ImageField(upload_to="plakaty", null=True, blank=True)
    video = models.FileField(upload_to="video", null=True, blank=True)

    def __str__(self):
        return self.tytul_z_rokiem()

    def tytul_z_rokiem(self):
        return "{} ({})".format(self.tytul, self.rok)

praca/filmyweb/forms.py
from django.forms import ModelForm
from .models import Film

class FilmForm(ModelForm):
    class Meta:
        model = Film
        fields = ['tytul', 'rok', 'opis', 'premiera', 'imdb_rating', 'plakat', 'video']

praca/filmyweb/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Film
from .forms import FilmForm
from django.contrib.auth.decorators import login_required


@login_required
def wszystkie_filmy(request):
    wszystkie = Film.objects.all()
    return render(request, 'filmy.html', {'filmy': wszystkie})


def nowy_film(request):
    form = FilmForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        form.save()
        return redirect(wszystkie_filmy)

    return render(request, 'film_form.html', {'form': form})


def edytuj_film(request, id):
    film = get_object_or_404(Film, pk=id)
    form = FilmForm(request.POST or None, request.FILES or None, instance=film)

    if form.is_valid():
        form.save()
        return redirect(wszystkie_filmy)

    return render(request, 'film_form.html', {'form': form})


def usun_film(request, id):
    film = get_object_or_404(Film, pk=id)
    if request.method == "POST":
        film.delete()
        return redirect(wszystkie_filmy)

    return render(request, 'potwierdz.html', {'film': film})

praca/templates/film_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>

body{
    background-color: black;
    margin: 5% 30%;
    color: white;
    font-size: 20px;

}
label{
    display: block;
    color: white;
    font-size: 20px;
    margin-top: 10px;
}
#id_tytul{
    top: 0;
    left: 5%;
    width: 100%;
    font-size: 30px;
    text-align: center;
    background-color: darkgray;
    border-radius: 5px;
}
#id_opis{
    width: 100%;
    background-color: darkgray;
    border-radius: 5px;
}
#id_rok{
    background-color: darkgray;
    border-radius: 5px;
}
#id_premiera{
    background-color: darkgray;
    border-radius: 5px;
}
#id_imdb_rating{
    background-color: darkgray;
    border-radius: 5px;
 }
label[for=plakat-clear_id] {
    display: inline;
}
label[for=plakat-clear_id]
#id_rok{
}
#plakat-clear_id{
    display: inline-block;

}
a{  display: inline-block;
    color: aliceblue;
    margin-left: 20px;
    margin-right: 20px;
}

        .btn{
            background-color: black;
            border: none;
            color: limegreen;
            padding: 5px 9px;
            font-size: 35px;
            cursor: pointer;
            position: absolute;
            top: 85%;
            left: 70%;
            border-radius: 5px;
        }
        .btn:hover{
            color: forestgreen;
        }
        .fa-chevron-left{
            background-color: black;
            border: none;
            color: dodgerblue;
            padding: 5px 9px;
            font-size: 35px;
            cursor: pointer;
            position: absolute;
            top: 85%;
            left: 30%;
            border-radius: 5px;
        }
        .fa-chevron-left:hover{
            color: royalblue;
        }
</style>
    <script src="https://kit.fontawesome.com/985d9b93c7.js" crossorigin="anonymous"></script>
</head>
<body>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
          {{ form }}
    <button type="submit" class="btn"> <i class="fas fa-plus"></i></button>
        </form>

    <a href="{% url 'wszystkie_filmy' %}"><i class="fas fa-chevron-left"></i></a>
</body>
</html>

praca/templates/filmy.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'moj.css' %}">
    <script src="https://kit.fontawesome.com/985d9b93c7.js" crossorigin="anonymous"></script>
    <style>
        .filmy{
    float: left;
}
body{
    background-color: black;
    margin: 0% 5%;
}
h2{
    text-align: center;
    font-size: 25px;
    font-family: "Roboto", "Lucida Grande", "DejaVu Sans", "Bitstream Vera Sans", Verdana, Arial, sans-serif;
    letter-spacing: 1px;
    text-transform: capitalize;
    color: crimson;
}

.plakat{
    margin-top: 50px;
    position: relative;
    float: left;
    z-index: 0;
    transition-duration: 0.3s;
}
.plakat:hover{
    z-index: 5;
}
.plakat img{
    height: 450px;
    width: 320px;
    margin: 10px;
    object-fit: cover;
    opacity : 0.70;
    transition-duration: 0.3s;

}
.plakat img:hover{
    opacity: 1;
    transform: scale(1.2);
    -webkit-transform: scale(1.2);
    -moz-transform: scale(1.2);


}


.hover{
    display: none;
    z-index: 5;
    background-color: black;
    position: fixed;
    top: 20px;
    left: 50%;
    transform: translateX(-50%);
    height: 90%;
    width: 80%;
}
.wrap{
    position: relative;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    overflow: hidden;
}
.video_v{
    display: block;
    position: absolute;
    top: 0;
    left: 0;
    height: 70vh;
    width: 100%;
}
.hover h3{
    display: inline-block;
    position: absolute;
    top: 75%;
    left: 50%;
    transform: translateX(-50%);
    color: white;
    text-align: center;
    font-size: 25px;

}
.hover p{
    display: inline-block;
    position: absolute;
    top: 78%;
    left: 50%;
    transform: translateX(-50%);
    padding: 50px;
    color: white;

}

.hover a{
    display: block;
    color: white;
    top: 90%;
    left:3%
}
.hover .edytuj{
    display: block;
    color: white;
    top: 87%;
    left:92%;
    transform: translateX(-50%);
}
.hover .usun{
    display: block;
    color: white;
    top: 87%;
    left:8%
}
.close{
    display: inline-block;
    position: absolute;
    top: 0%;
    right: 5%;
    color: white;
    z-index: 10;
    font-size: 25px;
    cursor: pointer;

}
i{
    font-size: 25px;
}
.fa-plus{
    display: block;
    font-size: 30px;
    position: absolute;
    top: 3%;
    left: 4%;
}
.fa-plus:hover{
    color: rebeccapurple;
}

.blur{
    height: 100vh;
    width: 100vw;
    position: fixed;
    top: -20px;
    left: -12%;
    background-color: black;
    opacity: 0.7;
}
.fa-times:hover{
    color: gray;
}
.fa-trash:hover{
    color: red;
}
.fa-edit:hover{
    color: rebeccapurple;
}
.logout{
    display: block;
    position: absolute;
    top: 6%;
    right: 5%;
    text-decoration: none;
    font-size: 20px;

}
.witaj{
    display: inline-block;
    position: absolute;
    top: 0%;
    right: 3%;
    text-transform: capitalize;
    font-size: 20px;
    color: whitesmoke;

}
    </style>
</head>
<body>
    <p class="witaj"> Witaj {{ user.username }}</p>
    <a class="logout" href="{% url 'logout' %}">Logout</a>
    <a href="{% url 'nowy_film' %}"><i class="fas fa-plus"></i></a>
    {% if filmy|length == 0%}
    <h2> Brak filmów </h2>
    {% else %}
    <h2> Ilość filmów : {{ filmy|length }} </h2>

    <div class="filmy">
    {% for film in filmy %}
        <div class="plakat">
        <img onclick="myFunction{{ film.id }}()" src="/media/{{ film.plakat }}">
        </div>

        <div id="plakat_{{ film.id }}" class="hover">
            <div class="wrap">
            <div class="blur" onclick="close_video{{ film.id }}()"></div>
            <div class="close" onclick="close_video{{ film.id }}()"><i class="fas fa-times"></i></div>
            <div class="video">
            <video class="video_v" id="video_{{ film.id }}" controls poster="/media/{{ film.plakat }}">
            <source src="/media/{{ film.video }}" type="video/mp4">
            Your browser does not support the video tag.
            </video>


            <div class="opis_filmu"></div>
            <h3>{{ film }}</h3>
            <p class="opis">{{ film.opis }}</p>
            <p class="edytuj"><a href="{% url 'edytuj_film' film.id %}"><i class="fas fa-edit"></i></a></p>
            <p class="usun"><a href="{% url 'usun_film' film.id %}"><i class="fas fa-trash"></i></a></p>
            </div>
            </div>
        </div>
</div>
    {% endfor %}
    {% endif %}
<script>
    {% for film in filmy %}
function myFunction{{ film.id }}(){
    document.getElementById("plakat_{{ film.id }}").style.display = "block" ;

}

function close_video{{ film.id }}(){
    document.getElementById("plakat_{{ film.id }}").style.display = "none" ;
    document.getElementById("video_{{ film.id }}").pause();
}
{% endfor %}
</script>
</body>
</html>

praca/templates/potwierdz.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://kit.fontawesome.com/985d9b93c7.js" crossorigin="anonymous"></script>
    <style>
        body{
            background-color: black;
            color: white;
            font-family: "Roboto", "Lucida Grande", "DejaVu Sans", "Bitstream Vera Sans", Verdana, Arial, sans-serif;
        }
        h1{
            text-align: center;
            font-size: 50px;
            margin-top: 10%;
        }
        .btn{
            background-color: red;
            border: none;
            color: white;
            padding: 12px 16px;
            font-size: 25px;
            cursor: pointer;
            position: absolute;
            top: 50%;
            left: 80%;
            border-radius: 5px;
        }
        .btn:hover {
            background-color: darkred;
        }
        .fa-chevron-left{
            display: block;
            position: absolute;
            top: 50%;
            left: 20%;
            font-size: 30px;
            color: white;
            padding: 12px 16px;
            background-color: dodgerblue;
            border-radius: 5px;
        }
        .fa-chevron-left:hover{
            background-color: royalblue;
        }
    </style>
</head>
<body>
 <h1>Czy na pewno usunąć "{{ film.tytul }}"?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn"><i class="fas fa-trash"></i></button>
    </form>
    <a href="{% url 'wszystkie_filmy' %}"><i class="fas fa-chevron-left"></i></a>
</body>
</html>